# Generated by Django 5.2.5 on 2025-09-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_comment_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
    ]
